// Code generated by wire. DO NOT EDIT.
// source: order.wire.go

package model

// OrderID is auto generated type
type OrderID int64

// OrderStatus is auto generated enum
type OrderStatus int

const (
	OrderStatusPending    OrderStatus = 1
	OrderStatusProcessing OrderStatus = 2
	OrderStatusCompleted  OrderStatus = 3
	OrderStatusCancelled  OrderStatus = 4
)

// String returns string representation
func (s OrderStatus) String() string {
	switch s {
	case OrderStatusPending:
		return "pending"
	case OrderStatusProcessing:
		return "processing"
	case OrderStatusCompleted:
		return "completed"
	case OrderStatusCancelled:
		return "cancelled"
	default:
		return "unknown"
	}
}
