// Code generated by go generate. DO NOT EDIT.

package model

// ProductID is auto generated type
type ProductID int64

// ProductCategory is auto generated enum
type ProductCategory int

const (
	ProductCategoryElectronics ProductCategory = 1
	ProductCategoryClothing    ProductCategory = 2
	ProductCategoryFood        ProductCategory = 3
)
