// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package model

// UserID is auto generated type
type UserID int64

// UserStatus is auto generated enum
type UserStatus int

const (
	UserStatusActive   UserStatus = 1
	UserStatusInactive UserStatus = 2
	UserStatusBanned   UserStatus = 3
)

// String returns string representation of UserStatus
func (s UserStatus) String() string {
	switch s {
	case UserStatusActive:
		return "active"
	case UserStatusInactive:
		return "inactive"
	case UserStatusBanned:
		return "banned"
	default:
		return "unknown"
	}
}
